<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.arnold.ace</groupId>
        <artifactId>acesonarplugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>sonar-esql-plugin</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.sonarsource.api.plugin</groupId>
            <artifactId>sonar-plugin-api</artifactId>
            <version>${sonar.api.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>