name: SonarQube

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'

  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    environment: SonarQube   # 👈 revisa que coincida EXACTO
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: mvn clean verify

      - name: Debug Sonar URL
        run: echo $SONAR_HOST_URL
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Sonar Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}